---
version: '3'
services:

# START SERVICE hkvb/ccloudmetrics
  ccloudexporter:
    image: ${VCW_REGISTRY}dabz/ccloudexporter:latest
    environment: ['CCLOUD_API_KEY=${MODULE_MODULE_CCLOUD_API_KEY}','CCLOUD_API_SECRET=${MODULE_MODULE_CCLOUD_SECRET_KEY}','CCLOUD_CLUSTER=${MODULE_MODULE_CCLOUD_CLUSTER}','CCLOUD_CONNECTOR=${MODULE_MODULE_CCLOUD_CONNECTOR}','CCLOUD_KSQL=${MODULE_MODULE_CCLOUD_KSQL}','CCLOUD_SCHEMA_REGISTRY=${MODULE_MODULE_CCLOUD_SCHEMA_REGISTRY}']
    command: []
    volumes: []
    ports: [2112:2112]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${MODULE_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${MODULE_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${MODULE_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/ccloudmetrics

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
